# Generated by Django 4.1.5 on 2023-01-24 10:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pintrestapp', '0002_post_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('mobilenumber', models.IntegerField()),
                ('profileimage', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=100, null=True)),
            ],
        ),
    ]
