# Generated by Django 4.1.5 on 2023-01-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pintrestapp', '0003_userdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='mobilenumber',
            new_name='phonenumber',
        ),
    ]
