# Generated by Django 4.1.5 on 2023-01-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pintrestapp', '0004_rename_mobilenumber_userdetails_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uploadby',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
