# Generated by Django 4.1.5 on 2023-02-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pintrestapp', '0009_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
    ]
